# SwiftLint Configuration for Lapses iOS
# Practical configuration that balances code quality with development velocity

# Paths to include
included:
  - outfind/lapses
  - outfind/lapsesTests

# Paths to exclude
excluded:
  - outfind/lapses.xcodeproj
  - "**/.build"
  - "**/DerivedData"
  - "**/Pods"

# Disabled rules - these are too strict or don't match project style
disabled_rules:
  - todo
  - trailing_comma
  - opening_brace
  - trailing_newline                           # False positives in CI environment
  - identifier_name
  - file_header                              # Project doesn't use consistent headers
  - switch_case_on_newline                   # Inline cases are fine for simple switches
  - type_contents_order                      # SwiftUI views have different ordering needs
  - attributes                               # @State/@Binding on same line is idiomatic SwiftUI
  - force_unwrapping                         # Sometimes necessary, rely on code review
  - number_separator                         # Not required for readability
  - prefer_self_in_static_references         # Type name is often clearer
  - closure_body_length                      # SwiftUI views often have long bodies
  - vertical_whitespace_opening_braces       # Style preference
  - vertical_whitespace_closing_braces       # Style preference
  - sorted_imports                           # Not critical
  - pattern_matching_keywords                # Style preference
  - redundant_type_annotation                # Sometimes adds clarity
  - type_name                                # Allow flexibility in naming
  - large_tuple                              # Sometimes needed
  - function_default_parameter_at_end        # SwiftUI patterns often break this
  - legacy_multiple                          # % operator is familiar
  - identical_operands                       # Can be intentional in tests
  - unneeded_synthesized_initializer         # Explicit init can improve readability
  - unused_closure_parameter                 # Common in tests and SwiftUI previews
  - multiple_closures_with_trailing_closure  # SwiftUI uses trailing closures extensively
  - leading_whitespace                       # False positives in CI
  - vertical_whitespace                      # Style preference

# Keep these important rules enabled (opt-in)
opt_in_rules:
  - empty_string
  - fatal_error_message
  - first_where
  - last_where
  - modifier_order
  - overridden_super_call
  - private_action
  - private_outlet
  - redundant_nil_coalescing
  - toggle_bool
  - unavailable_function
  - xct_specific_matcher
  - yoda_condition

# Rule configurations
line_length:
  warning: 150
  error: 200
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true
  ignores_interpolated_strings: true

file_length:
  warning: 1500
  error: 2000
  ignore_comment_only_lines: true

type_body_length:
  warning: 400
  error: 600

function_body_length:
  warning: 80
  error: 150

function_parameter_count:
  warning: 8
  error: 10
  ignores_default_parameters: true

cyclomatic_complexity:
  warning: 15
  error: 25
  ignores_case_statements: true

nesting:
  type_level:
    warning: 4
    error: 6
  function_level:
    warning: 5
    error: 8

# Custom rules
custom_rules:
  no_print_statements:
    included: ".*\\.swift"
    excluded: ".*Tests?\\.swift"
    name: "No print() statements"
    regex: "\\bprint\\s*\\("
    message: "Avoid using print() in production code. Use proper logging instead."
    severity: warning

  avoid_nslog:
    included: ".*\\.swift"
    name: "Avoid NSLog"
    regex: "\\bNSLog\\s*\\("
    message: "Avoid NSLog in Swift code. Use os.Logger or proper logging."
    severity: warning

# Reporter type
reporter: "xcode"
